In [1]:
print("hlo data science")

hlo data science

In [4]:
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.3.4
Pandas version: 2.3.3

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr + 10)
print(arr * 2)
print(arr / 5)

[20 30 40 50]
[20 40 60 80]
[2. 4. 6. 8.]

In [1]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30])

print(arr[0:3])     # first 3 elements
print(arr[2:5])     # elements from index 2 to 4
print(arr[-2:])     # last 2 elements

[ 5 10 15]
[15 20 25]
[25 30]

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)

print("Original:", arr)
print("Reshaped:\n", reshaped)

Original: [1 2 3 4 5 6]
Reshaped:
 [[1 2 3]
 [4 5 6]]

In [3]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Kunal"],
    "Age": [21, 24, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

    Name  Age    City
0   Aman   21   Delhi
1   Riya   24  Mumbai
2  Kunal   20    Pune

In [7]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Kunal"],
    "Age": [21, 24, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df.index = df.index + 1  # start index from 1

print(df)
df.head()
df.info()
df.describe()

    Name  Age    City
1   Aman   21   Delhi
2   Riya   24  Mumbai
3  Kunal   20    Pune
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

             Age
count   3.000000
mean   21.666667
std     2.081666
min    20.000000
25%    20.500000
50%    21.000000
75%    22.500000
max    24.000000

In [14]:
import pandas as pd

data = {
    "Name": ["Amit", "Riya", "Karan", "Sara", "John"],
    "Age": [21, 25, 19, 23, 30],
    "Marks": [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data)
df.head()      # first 5 rows
df.tail()      # last 5 rows

    Name  Age  Marks
0   Amit   21     85
1   Riya   25     90
2  Karan   19     78
3   Sara   23     88
4   John   30     92

In [1]:
# Pandas :

In [2]:
# What is Pandas?
# Pandas is a Python library used for working with data sets.

# It has functions for analyzing, cleaning, exploring, and manipulating data.

# The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

In [3]:
# Why Use Pandas?
# Pandas allows us to analyze big data and make conclusions based on statistical theories.

# Pandas can clean messy data sets, and make them readable and relevant.

# Relevant data is very important in data science.

In [4]:
# What Can Pandas Do?
# Pandas gives you answers about the data. Like:

# Is there a correlation between two or more columns?
# What is average value?
# Max value?
# Min value?
# Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

In [5]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [6]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [7]:
# Checking Pandas Version :
import pandas as pd

print(pd.__version__)

3.0.2

In [1]:
# Pandas Series :

In [2]:
# What is a Series?
# A Pandas Series is like a column in a table.

# It is a one-dimensional array holding data of any type.

In [3]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64

In [4]:
# Labels
# If nothing else is specified, the values are labeled with their index number. First value has index 0, second value has index 1 etc.

# This label can be used to access a specified value.

In [5]:
print(myvar[0])

1

In [7]:
# Create Labels
# With the index argument, you can name your own labels.
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [8]:
print(myvar["y"])

7

In [9]:
# Key/Value Objects as Series :
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [10]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64

In [11]:
# DataFrames
# Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

# Series is like a column, a DataFrame is the whole table.

In [12]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45

In [1]:
# Pandas DataFrames :

In [2]:
# What is a DataFrame?
# A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [3]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [4]:
# Locate Row
# As you can see from the result above, the DataFrame is like a table with rows and columns.

# Pandas use the loc attribute to return one or more specified row(s)

In [5]:
#refer to the row index:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [6]:
#use a list of indexes:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40

In [7]:
# Named Indexes
# With the index argument, you can name your own indexes.

In [8]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [9]:
# Locate Named Indexes
# Use the named index in the loc attribute to return the specified row(s).

In [10]:
#refer to the named index:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64

In [12]:
# Load Files Into a DataFrame
# If your data sets are stored in a file, Pandas can load them into a DataFrame.

In [2]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df)

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]